# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Croesus' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Croesus
pod 'Firebase/Core'	
  target 'CroesusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CroesusUITests' do
    # Pods for testing
  end

end
