# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Croesus' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Croesus
  pod 'Firebase/Core', :inhibit_warnings => true
  pod 'Firebase/Database', :inhibit_warnings => true
  pod 'Firebase/Auth', :inhibit_warnings => true
  pod 'SWActivityIndicatorView'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'KeychainAccess'	
  pod 'surveymonkey-ios-sdk', '~> 2.0'
  target 'CroesusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CroesusUITests' do
    # Pods for testing
  end

end
